// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	llmdrouterapixv1alpha2 "github.com/llm-d/llm-d-router/apix/v1alpha2"
	versioned "github.com/llm-d/llm-d-router/client-go/clientset/versioned"
	internalinterfaces "github.com/llm-d/llm-d-router/client-go/informers/externalversions/internalinterfaces"
	apixv1alpha2 "github.com/llm-d/llm-d-router/client-go/listers/apix/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InferenceModelRewriteInformer provides access to a shared informer and lister for
// InferenceModelRewrites.
type InferenceModelRewriteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apixv1alpha2.InferenceModelRewriteLister
}

type inferenceModelRewriteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInferenceModelRewriteInformer constructs a new informer for InferenceModelRewrite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceModelRewriteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewInferenceModelRewriteInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredInferenceModelRewriteInformer constructs a new informer for InferenceModelRewrite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInferenceModelRewriteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewInferenceModelRewriteInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewInferenceModelRewriteInformerWithOptions constructs a new informer for InferenceModelRewrite type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceModelRewriteInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "llm-d.ai", Version: "v1alpha2", Resource: "inferencemodelrewrites"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).Watch(ctx, opts)
			},
		}, client),
		&llmdrouterapixv1alpha2.InferenceModelRewrite{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *inferenceModelRewriteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewInferenceModelRewriteInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *inferenceModelRewriteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&llmdrouterapixv1alpha2.InferenceModelRewrite{}, f.defaultInformer)
}

func (f *inferenceModelRewriteInformer) Lister() apixv1alpha2.InferenceModelRewriteLister {
	return apixv1alpha2.NewInferenceModelRewriteLister(f.Informer().GetIndexer())
}
