# Go build stage
FROM registry.access.redhat.com/ubi9/go-toolset:1.26.5@sha256:f99dd81b20e5971ef9f63a51ac27cf0aa591ff9921d021490548b67fd9b17144 AS go-builder

ARG TARGETOS
ARG TARGETARCH
ARG COMMIT_SHA=unknown
ARG BUILD_REF
ARG LDFLAGS="-s -w"

USER root

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Download dependencies - this layer is cached as long as go.mod/go.sum are unchanged
RUN go mod download

# Copy the go source
COPY apix/     apix/
COPY cmd/      cmd/
COPY internal/ internal/
COPY pkg/      pkg/
COPY version/  version/

RUN go mod download

# Build EPP
RUN CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build \
       -ldflags="${LDFLAGS} -X github.com/llm-d/llm-d-router/version.CommitSHA=${COMMIT_SHA} -X github.com/llm-d/llm-d-router/version.BuildRef=${BUILD_REF}" \
       -o bin/epp cmd/epp/main.go

# Runtime stage
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:907b68736aa798b2d38255b7aa070b2a70acb90803864a40f05d0ec47556ddd0

WORKDIR /

COPY --from=go-builder /workspace/bin/epp /app/epp

USER 65532:65532

# expose gRPC, health and metrics ports
EXPOSE 9002
EXPOSE 9003
EXPOSE 9090
# expose port for KV-Events ZMQ SUB socket
EXPOSE 5557

ENTRYPOINT ["/app/epp"]

LABEL com.redhat.component="odh-llm-d-inference-scheduler" \
      name="odh-llm-d-inference-scheduler" \
      description="odh-llm-d-inference-scheduler" \
      summary="odh-llm-d-inference-scheduler" \
      io.k8s.display-name="odh-llm-d-inference-scheduler" \
      io.k8s.description="odh-llm-d-inference-scheduler"