// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	llmdrouterapixv1 "github.com/llm-d/llm-d-router/apix/v1"
	versioned "github.com/llm-d/llm-d-router/client-go/clientset/versioned"
	internalinterfaces "github.com/llm-d/llm-d-router/client-go/informers/externalversions/internalinterfaces"
	apixv1 "github.com/llm-d/llm-d-router/client-go/listers/apix/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InferenceObjectiveInformer provides access to a shared informer and lister for
// InferenceObjectives.
type InferenceObjectiveInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apixv1.InferenceObjectiveLister
}

type inferenceObjectiveInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInferenceObjectiveInformer constructs a new informer for InferenceObjective type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceObjectiveInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewInferenceObjectiveInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredInferenceObjectiveInformer constructs a new informer for InferenceObjective type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInferenceObjectiveInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewInferenceObjectiveInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewInferenceObjectiveInformerWithOptions constructs a new informer for InferenceObjective type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceObjectiveInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "llm-d.ai", Version: "v1", Resource: "inferenceobjectives"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1().InferenceObjectives(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1().InferenceObjectives(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1().InferenceObjectives(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.XInferenceV1().InferenceObjectives(namespace).Watch(ctx, opts)
			},
		}, client),
		&llmdrouterapixv1.InferenceObjective{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *inferenceObjectiveInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewInferenceObjectiveInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *inferenceObjectiveInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&llmdrouterapixv1.InferenceObjective{}, f.defaultInformer)
}

func (f *inferenceObjectiveInformer) Lister() apixv1.InferenceObjectiveLister {
	return apixv1.NewInferenceObjectiveLister(f.Informer().GetIndexer())
}
