// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/llm-d/llm-d-router/apix/v1"
	apixv1 "github.com/llm-d/llm-d-router/client-go/applyconfiguration/apix/v1"
	typedapixv1 "github.com/llm-d/llm-d-router/client-go/clientset/versioned/typed/apix/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInferenceObjectives implements InferenceObjectiveInterface
type fakeInferenceObjectives struct {
	*gentype.FakeClientWithListAndApply[*v1.InferenceObjective, *v1.InferenceObjectiveList, *apixv1.InferenceObjectiveApplyConfiguration]
	Fake *FakeXInferenceV1
}

func newFakeInferenceObjectives(fake *FakeXInferenceV1, namespace string) typedapixv1.InferenceObjectiveInterface {
	return &fakeInferenceObjectives{
		gentype.NewFakeClientWithListAndApply[*v1.InferenceObjective, *v1.InferenceObjectiveList, *apixv1.InferenceObjectiveApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("inferenceobjectives"),
			v1.SchemeGroupVersion.WithKind("InferenceObjective"),
			func() *v1.InferenceObjective { return &v1.InferenceObjective{} },
			func() *v1.InferenceObjectiveList { return &v1.InferenceObjectiveList{} },
			func(dst, src *v1.InferenceObjectiveList) { dst.ListMeta = src.ListMeta },
			func(list *v1.InferenceObjectiveList) []*v1.InferenceObjective {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.InferenceObjectiveList, items []*v1.InferenceObjective) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
