// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/llm-d/llm-d-router/client-go/clientset/versioned/typed/apix/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeXInferenceV1 struct {
	*testing.Fake
}

func (c *FakeXInferenceV1) InferenceObjectives(namespace string) v1.InferenceObjectiveInterface {
	return newFakeInferenceObjectives(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeXInferenceV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
