// Code generated by lister-gen. DO NOT EDIT.

package v1

// InferenceObjectiveListerExpansion allows custom methods to be added to
// InferenceObjectiveLister.
type InferenceObjectiveListerExpansion interface{}

// InferenceObjectiveNamespaceListerExpansion allows custom methods to be added to
// InferenceObjectiveNamespaceLister.
type InferenceObjectiveNamespaceListerExpansion interface{}
