// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apixv1 "github.com/llm-d/llm-d-router/apix/v1"
)

// PoolObjectReferenceApplyConfiguration represents a declarative configuration of the PoolObjectReference type for use
// with apply.
//
// PoolObjectReference identifies an API object within the namespace of the
// referrer.
type PoolObjectReferenceApplyConfiguration struct {
	// Group is the group of the referent.
	Group *apixv1.Group `json:"group,omitempty"`
	// Kind is kind of the referent. For example "InferencePool".
	Kind *apixv1.Kind `json:"kind,omitempty"`
	// Name is the name of the referent.
	Name *apixv1.ObjectName `json:"name,omitempty"`
}

// PoolObjectReferenceApplyConfiguration constructs a declarative configuration of the PoolObjectReference type for use with
// apply.
func PoolObjectReference() *PoolObjectReferenceApplyConfiguration {
	return &PoolObjectReferenceApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *PoolObjectReferenceApplyConfiguration) WithGroup(value apixv1.Group) *PoolObjectReferenceApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PoolObjectReferenceApplyConfiguration) WithKind(value apixv1.Kind) *PoolObjectReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PoolObjectReferenceApplyConfiguration) WithName(value apixv1.ObjectName) *PoolObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}
