// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	apixv1 "github.com/llm-d/llm-d-router/apix/v1"
	scheme "github.com/llm-d/llm-d-router/client-go/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type XInferenceV1Interface interface {
	RESTClient() rest.Interface
	InferenceObjectivesGetter
}

// XInferenceV1Client is used to interact with features provided by the llm-d.ai group.
type XInferenceV1Client struct {
	restClient rest.Interface
}

func (c *XInferenceV1Client) InferenceObjectives(namespace string) InferenceObjectiveInterface {
	return newInferenceObjectives(c, namespace)
}

// NewForConfig creates a new XInferenceV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*XInferenceV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new XInferenceV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*XInferenceV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &XInferenceV1Client{client}, nil
}

// NewForConfigOrDie creates a new XInferenceV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *XInferenceV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new XInferenceV1Client for the given RESTClient.
func New(c rest.Interface) *XInferenceV1Client {
	return &XInferenceV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apixv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *XInferenceV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
