// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	apixv1 "github.com/llm-d/llm-d-router/apix/v1"
	applyconfigurationapixv1 "github.com/llm-d/llm-d-router/client-go/applyconfiguration/apix/v1"
	scheme "github.com/llm-d/llm-d-router/client-go/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferenceObjectivesGetter has a method to return a InferenceObjectiveInterface.
// A group's client should implement this interface.
type InferenceObjectivesGetter interface {
	InferenceObjectives(namespace string) InferenceObjectiveInterface
}

// InferenceObjectiveInterface has methods to work with InferenceObjective resources.
type InferenceObjectiveInterface interface {
	Create(ctx context.Context, inferenceObjective *apixv1.InferenceObjective, opts metav1.CreateOptions) (*apixv1.InferenceObjective, error)
	Update(ctx context.Context, inferenceObjective *apixv1.InferenceObjective, opts metav1.UpdateOptions) (*apixv1.InferenceObjective, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferenceObjective *apixv1.InferenceObjective, opts metav1.UpdateOptions) (*apixv1.InferenceObjective, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apixv1.InferenceObjective, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apixv1.InferenceObjectiveList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apixv1.InferenceObjective, err error)
	Apply(ctx context.Context, inferenceObjective *applyconfigurationapixv1.InferenceObjectiveApplyConfiguration, opts metav1.ApplyOptions) (result *apixv1.InferenceObjective, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inferenceObjective *applyconfigurationapixv1.InferenceObjectiveApplyConfiguration, opts metav1.ApplyOptions) (result *apixv1.InferenceObjective, err error)
	InferenceObjectiveExpansion
}

// inferenceObjectives implements InferenceObjectiveInterface
type inferenceObjectives struct {
	*gentype.ClientWithListAndApply[*apixv1.InferenceObjective, *apixv1.InferenceObjectiveList, *applyconfigurationapixv1.InferenceObjectiveApplyConfiguration]
}

// newInferenceObjectives returns a InferenceObjectives
func newInferenceObjectives(c *XInferenceV1Client, namespace string) *inferenceObjectives {
	return &inferenceObjectives{
		gentype.NewClientWithListAndApply[*apixv1.InferenceObjective, *apixv1.InferenceObjectiveList, *applyconfigurationapixv1.InferenceObjectiveApplyConfiguration](
			"inferenceobjectives",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apixv1.InferenceObjective { return &apixv1.InferenceObjective{} },
			func() *apixv1.InferenceObjectiveList { return &apixv1.InferenceObjectiveList{} },
		),
	}
}
